/**
 * Codegen: PB-снапшот `.pb/*.json` → TS-литералы `src/shared/content/*.ts`.
 * Запускается автоматически перед билдом (см. package.json prebuild).
 *
 * Почему codegen, а не runtime fs.readFileSync:
 * — некоторые client-компоненты импортируют CONTACTS/YACHTS для UI-логики,
 *   fs в браузере не работает; литералы bundler'ом инлайнятся, работает везде.
 * — сохраняем zod-валидацию: если PB отдаёт битую форму, codegen падает
 *   на этапе билда, а не в проде.
 *
 * Каждый файл: `export const X = <literal> as const;` + type re-export для
 * consumers, которые до сих пор импортируют `type X` из этого модуля.
 */
import {
  Certificate,
  Contacts,
  FaqItem,
  InstagramStory,
  LegalDocument,
  Service,
  Yacht,
} from "@moreminsk/pb-client";
import * as fs from "node:fs";
import * as path from "node:path";
import type { ZodType } from "zod";
import { z } from "zod";

const ROOT = path.resolve(process.cwd());
const SNAP = path.join(ROOT, ".pb");
const OUT = path.join(ROOT, "src/shared/content");

function readJson(name: string): unknown {
  const p = path.join(SNAP, `${name}.json`);
  if (!fs.existsSync(p)) {
    throw new Error(`snapshot missing: ${p} — run 'bun run pb:export' first`);
  }
  return JSON.parse(fs.readFileSync(p, "utf8"));
}

function stringify(v: unknown): string {
  return JSON.stringify(v, null, 2);
}

type Target<T> = {
  file: string;
  constName: string;
  /** Тип из @moreminsk/pb-client — им аннотируем const, чтобы получить широкий
   *  тип FaqItem[] вместо narrow-литерала. */
  typeName: string;
  isArray: boolean;
  schema: ZodType<T>;
  collection: string;
  typeReexports?: string[]; // дополнительные типы для реэкспорта из pb-client
};

const TARGETS: Target<unknown>[] = [
  {
    file: "yachts.ts",
    constName: "YACHTS",
    typeName: "Yacht",
    isArray: true,
    collection: "yachts",
    schema: z.array(Yacht),
  },
  {
    file: "services.ts",
    constName: "SERVICES",
    typeName: "Service",
    isArray: true,
    collection: "services",
    schema: z.array(Service),
  },
  {
    file: "faq.ts",
    constName: "FAQ",
    typeName: "FaqItem",
    isArray: true,
    collection: "faq",
    schema: z.array(FaqItem),
  },
  {
    file: "documents.ts",
    constName: "DOCUMENTS",
    typeName: "LegalDocument",
    isArray: true,
    collection: "documents",
    schema: z.array(LegalDocument),
  },
  {
    file: "instagram-stories.ts",
    constName: "INSTAGRAM_STORIES",
    typeName: "InstagramStory",
    isArray: true,
    collection: "instagram_stories",
    schema: z.array(InstagramStory),
  },
  {
    file: "certificates.ts",
    constName: "CERTIFICATE",
    typeName: "Certificate",
    isArray: false,
    collection: "certificates",
    schema: Certificate,
    typeReexports: ["CertFaqItem"],
  },
  {
    file: "contacts.ts",
    constName: "CONTACTS",
    typeName: "Contacts",
    isArray: false,
    collection: "contacts",
    schema: Contacts,
  },
];

fs.mkdirSync(OUT, { recursive: true });

for (const t of TARGETS) {
  const raw = readJson(t.collection);
  const parsed = t.schema.parse(raw);
  // Импортируем только primary type — им аннотируем const.
  const typeImport = `import type { ${t.typeName} } from "@moreminsk/pb-client";\n`;
  // primary + доп-типы реэкспортируем ОТДЕЛЬНО (export type from), consumers пишут
  // `import { FAQ, FaqItem } from "@/shared/content/faq";`.
  const reexports = [t.typeName, ...(t.typeReexports ?? [])];
  const reexport = `export type { ${reexports.join(", ")} } from "@moreminsk/pb-client";\n`;
  const typeAnnot = t.isArray ? `readonly ${t.typeName}[]` : t.typeName;
  const banner =
    `// AUTO-GENERATED by scripts/pb/codegen.ts из .pb/${t.collection}.json.\n` +
    `// Не редактировать вручную — правки в PocketBase → pb:export → pb:codegen.\n\n`;
  const body = `${typeImport}${reexport}\nexport const ${t.constName}: ${typeAnnot} = ${stringify(parsed)};\n`;
  fs.writeFileSync(path.join(OUT, t.file), banner + body);
  console.log(`✓ ${t.file}`);
}

console.log("done");
