// AUTO-GENERATED by scripts/pb/codegen.ts из .pb/certificates.json.
// Не редактировать вручную — правки в PocketBase → pb:export → pb:codegen.

import type { Certificate } from "@moreminsk/pb-client";
export type { CertFaqItem, Certificate } from "@moreminsk/pb-client";

export const CERTIFICATE: Certificate = {
  priceFrom: 150,
  season: "1 мая — 30 сентября",
  lead: "Не знаете, что подарить? Сертификат на прогулку под парусом или мотором по Минскому морю — впечатление вместо вещи.",
  offer: [
    "Подарок на день рождения, годовщину, девичник или без повода — получатель сам выбирает дату и яхту.",
    "Парусные EVA, ALFA, BRAVO или моторная MARIO — прогулка на 1, 2 или 3 часа. Капитан и топливо уже в цене.",
    "Оформим за пару минут и передадим электронным или печатным бланком.",
  ],
  photos: [
    "/certificates/bouquet.jpg",
    "/certificates/roses.jpg",
    "/certificates/cards.jpg",
    "/certificates/basket.jpg",
  ],
  photoAlts: [
    "Букет цветов с подарочным сертификатом на яхту",
    "Подарочный сертификат на палубе с букетом роз",
    "Печатные бланки подарочного сертификата",
    "Букет роз на палубе яхты — подарок с сертификатом",
  ],
  faq: [
    {
      id: "cert-validity",
      question: "Какой срок действия сертификата?",
      answer: "Весь парусный сезон — с 1 мая по 30 сентября текущего года.",
    },
    {
      id: "cert-how",
      question: "Как заказать сертификат?",
      answer:
        "Оставьте заявку через форму на этой странице или напишите в Telegram @moreminsk / позвоните. Оформим и передадим электронным или печатным бланком.",
    },
    {
      id: "cert-types",
      question: "Какие виды сертификатов?",
      answer:
        "На прогулку по Минскому морю — парусную (EVA, ALFA, BRAVO) или моторную (MARIO), на 1, 2 или 3 часа. Номинал — от 150 BYN.",
    },
    {
      id: "cert-where",
      question: "Где вы находитесь?",
      answer:
        "Причал в Ждановичах, ул. Вокзальная 8а (д. Качино) — 25 минут на машине от центра Минска, парковка бесплатная.",
    },
  ],
};
