// AUTO-GENERATED by scripts/pb/codegen.ts из .pb/contacts.json.
// Не редактировать вручную — правки в PocketBase → pb:export → pb:codegen.

import type { Contacts } from "@moreminsk/pb-client";
export type { Contacts } from "@moreminsk/pb-client";

export const CONTACTS: Contacts = {
  phones: [
    {
      label: "+375 29 695 36 36",
      href: "tel:+375296953636",
      primary: true,
    },
    {
      label: "+375 29 6 109 107",
      href: "tel:+375296109107",
    },
  ],
  email: {
    label: "9797-7@mail.ru",
    href: "mailto:9797-7@mail.ru",
  },
  telegram: {
    label: "@moreminsk",
    href: "https://t.me/moreminsk",
  },
  instagram: {
    label: "@moreminsk.by",
    href: "https://instagram.com/moreminsk.by",
  },
  viber: {
    label: "+375 29 695 36 36",
    href: "viber://chat?number=%2B375296953636",
  },
  address: {
    line1: "Ждановичский с/с, д. Качино, ул. Вокзальная 8а",
    line2: "25 минут от центра Минска",
    hours: "Ежедневно 9:00–22:00",
    mapsUrl: "https://yandex.by/maps/?ll=27.371164,53.953826&z=16&pt=27.371164,53.953826",
  },
  legal: {
    entity: "ИП Киселёва И.А.",
    unp: "590078696",
    legalAddress: "220033, Минск, ул. Фабричная, 30-100",
    registeredAt: "2010-10-11",
    bank: {
      account: "BY89MTBK30130001093300027992",
      currency: "BYN",
      name: "ЗАО «МТБанк»",
      bic: "MTBKBY22",
    },
  },
  yandex: {
    oid: "193210462372",
    coords: {
      lat: 53.953826,
      lon: 27.371164,
    },
  },
};
